#pragma config(Sensor, in1, leftArmPot, sensorPotentiometer)
#pragma config(Sensor, in2, rightArmPot, sensorPotentiometer)
#pragma config(Sensor, in3, clawPot, sensorPotentiometer)
#pragma config(Sensor, in4, gyro, sensorGyro)
#pragma config(Sensor, dgtl1, yWheelEncoder1, sensorQuadEncoder)
#pragma config(Sensor, dgtl3, xWheelEncoder1, sensorQuadEncoder)
#pragma config(Motor,  port1, frontLeftWheel, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2, backLeftWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3, frontRightWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4, backRightWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5, topLeftArm,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6, bottomLeftArm, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7, topRightArm,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8, bottomRightArm, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9, clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10, coneMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//functions
void grabCone(){;}
void dropCone(){;}
void top(){;}
void btm(){;}
void nogo()
{
	motor[frontLeftWheel] = motor[frontRightWheel] = 0;
	motor[backLeftWheel] = motor[backRightWheel] = 0;
}
void move(){;}
void lift(){;}
void cad(){;}//cease and desist

task main()
{
	while(true)
	{
		//variables
		int X1 = 0, Y1 = 0, X2 = 0;
		int threshold = 15;
	//	int speed[] = {0, 64, 128, 192, 256};
		//wheel control
		//create deadzones
		if(abs(vexRT[Ch3]) > threshold) Y1 = vexRT[Ch3];
		else Y1 = 0;
		if(abs(vexRT[Ch4]) > threshold) X1 = vexRT[Ch4];
		else Y1 = 0;
		if(abs(vexRT[Ch1]) > threshold) X2 = vexRT[Ch1];
		else X2 = 0;
		//remote control
		motor[frontRightWheel] = Y1 + X2 - X1;//3+1-4
		motor[backRightWheel] = Y1 + X2 + X1;//3+1+4
		motor[frontLeftWheel] = Y1 - X2 + X1;//3-1+4
		motor[backLeftWheel] = Y1 - X2 - X1; //3-1-4

		//arm control
		if(vexRT[Btn5U] == 1)
		{
			motor[topLeftArm] = 100;
			motor[bottomLeftArm] = 100;
			motor[topRightArm] = 100;
			motor[bottomRightArm] = 100;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[topLeftArm] = -100;
			motor[bottomLeftArm] = -100;
			motor[topRightArm] = -100;
			motor[bottomRightArm] = -100;
		}
		else
		{
			motor[topLeftArm] = 0;
			motor[bottomLeftArm] = 0;
			motor[topRightArm] = 0;
			motor[bottomRightArm] = 0;
		}

		//claw control
		if(vexRT[Btn6U] == 1)	motor[clawMotor] = 100;
		else if(vexRT[Btn6D] == 1) motor[clawMotor] = -100;
		else motor[clawMotor] = 0;


		//cone lift control
		if(vexRT[Btn7U] == 1)	motor[coneMotor] = 100;
		else if(vexRT[Btn7D] == 1)	motor[coneMotor] = -100;
		else	motor[coneMotor] = 0;

	}
}
