#pragma config(Sensor, in1,    leftArmPot,     sensorPotentiometer)
#pragma config(Sensor, in2,    rightArmPot,    sensorPotentiometer)
#pragma config(Sensor, in3,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  yWheelEncoder1, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  xWheelEncoder1, sensorQuadEncoder)
#pragma config(Motor,  port1,           frontLeftWheel, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           backLeftWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRightWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backRightWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           topLeftArm,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           bottomLeftArm, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           topRightArm,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           bottomRightArm, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          coneMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){

		motor[frontLeftWheel] = vexRT[Ch3];
		motor[backLeftWheel] = vexRT[Ch3];
		motor[frontRightWheel] = vexRT[Ch3];
		motor[backRightWheel] = vexRT[Ch3];

		//arm control
		if(vexRT[Btn5U] == 1){

			motor[topLeftArm] = 100;
			motor[bottomLeftArm] = 100;
			motor[topRightArm] = 100;
			motor[bottomRightArm] = 100;

		}else if(vexRT[Btn5D] == 1){

			motor[topLeftArm] = -100;
			motor[bottomLeftArm] = -100;
			motor[topRightArm] = -100;
			motor[bottomRightArm] = -100;

		}else{

			motor[topLeftArm] = 0;
			motor[bottomLeftArm] = 0;
			motor[topRightArm] = 0;
			motor[bottomRightArm] = 0;

		}

		//claw control
		if(vexRT[Btn6U] == 1)
			motor[clawMotor] = 100;
		else if(vexRT[Btn6D] == 1)
			motor[clawMotor] = -100;
		else
			motor[clawMotor] = 0;


		//cone lift control
		if(vexRT[Btn7U] == 1)
			motor[coneMotor] = 100;
		else if(vexRT[Btn7D] == 1)
			motor[coneMotor] = -100;
		else
			motor[coneMotor] = 0;

	}
}
