#pragma config(Sensor, in1, leftArmPot, sensorPotentiometer)
#pragma config(Sensor, in2, rightArmPot, sensorPotentiometer)
#pragma config(Sensor, in3, clawPot, sensorPotentiometer)
#pragma config(Sensor, in4, gyro, sensorGyro)
#pragma config(Sensor, dgtl1, yDir, sensorQuadEncoder)
#pragma config(Sensor, dgtl3, xDir, sensorQuadEncoder)
#pragma config(Motor,  port1, frontLeftWheel, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2, backLeftWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3, frontRightWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4, backRightWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5, topLeftArm,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6, bottomLeftArm, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7, topRightArm,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8, bottomRightArm, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9, clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10, coneMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*********************************************************************************/
	int run = 0, test = 0;
	void readSensors(int steps, int choice)
	{
		for(int i = 0; i < steps; i++)
		{
			writeDebugStreamLine("---------Testing %s, Run %d, Step #%d---------",choice, run, steps);
			switch(choice)
			{
				case 0:
							writeDebugStream("Encoders = (%d", SensorValue[xDir]);
							writeDebugStreamLine(", %d)", SensorValue[yDir]);
							break;
				case 1:
							writeDebugStream("Arms: L= %d", SensorValue[leftArmPot]);
							writeDebugStreamLine("R = %d", SensorValue[rightArmPot]);
							break;
				case 2:
							writeDebugStreamLine("Claw: %d",SensorValue[clawPot]);
							break;
			}
			run++;
		}
	}

task main()
{
	/************************************************************************/
	//Clear out the previous sensors
	SensorType[leftArmPot] = sensorNone;
	SensorType[rightArmPot] = sensorNone;
	SensorType[clawPot] = sensorNone;
	SensorType[gyro] = sensorNone;
	SensorType[yDir] = sensorNone;
	SensorType[xDir] = sensorNone;
	wait1Msec(1000);

	//Reconfigure Sensor Ports
	SensorType[leftArmPot] = sensorPotentiometer;
	SensorType[rightArmPot] = sensorPotentiometer;
	SensorType[clawPot] = sensorPotentiometer;
	SensorType[gyro] = sensorGyro;
	SensorType[yDir] = sensorQuadEncoder;
	SensorType[xDir] = sensorQuadEncoder;
	wait1Msec(1000);

	/*********************************************************************************/
	//WHEELS
	run = 0;
	test = 0;
	//the forward
	motor[backLeftWheel] = motor[backRightWheel] = 50;
	motor[frontLeftWheel] = motor[frontRightWheel] = 50;
	readSensors(20, test);
	//left
	motor[backLeftWheel] = motor[frontRightWheel] = -50;
	motor[frontLeftWheel] = motor[backRightWheel] = 50;
	readSensors(20, test);
	//right
	motor[backLeftWheel] = motor[frontRightWheel] = 50;
	motor[frontLeftWheel] = motor[backRightWheel] = -50;
	readSensors(20, test);
	//backward
	motor[backLeftWheel] = motor[backRightWheel] = -50;
	motor[frontLeftWheel] = motor[frontRightWheel] = -50;
	readSensors(20, test);
	//stop
	motor[backLeftWheel] = motor[backRightWheel] = 0;
	motor[frontLeftWheel] = motor[frontRightWheel] = 0;
	readSensors(5, test);
	/*****************************************************************************************/
	//CLAW
	run =  0;
	test = 1;
	//close
	motor[clawMotor] = 50;
	readSensors(20, test);
	//stop
	motor[clawMotor] = 0;
	readSensors(5, test);
	//open
	motor[clawMotor] = 50;
	readSensors(20, test);
	//stop
	motor[clawMotor] = 0;
	readSensors(5, test);

	/*******************************************************************************************/
	//ARM
	run = 0;
	test = 2;
	//up
	motor[topRightArm]	= motor[bottomRightArm]	=	50;
	motor[topLeftArm]		= motor[bottomLeftArm]	= 50;
	readSensors(20, test);
	//stop
	motor[topRightArm]	=	motor[bottomRightArm] = 0;
	motor[topLeftArm]		= motor[bottomLeftArm]	= 0;
	readSensors(5, test);
	//down
	motor[topRightArm]	= motor[bottomRightArm] = -50;
	motor[topLeftArm]		= motor[bottomLeftArm] 	= -50;
	readSensors(20, test);
	//stop
	motor[topRightArm]	= motor[bottomRightArm] = 0;
	motor[topLeftArm]		= motor[bottomLeftArm] 	= 0;
	readSensors(5, test);
}
